name: mindful_posture
description: "Aplicación móvil para mejorar la postura mediante recordatorios y sensores."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Estilo
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4

  # Sensores
  sensors_plus: ^7.0.0
  proximity_sensor: ^1.3.9
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
        - asset: assets/fonts/nunito/Nunito-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
